export const mutantsPowersList = [
    'Telepathy',
    'Telekinesis',
    'Time Travel',
    'Teleportation',
    'Invisibility',
    'Phoenix Force',
    'Time Manipulation',
    'Super Strength',
    'Super Speed',
    'Healing Factor',
    'Flight',
    'Force Field',
    'Energy Blast',
    'Elemental',
    'Elasticity',
    'Duplication',
    'Density Control',
    'Claws',
    'Chameleon',
    'Biokinesis',
    'Animal Mimicry',
    'Adaptation',
    'Acid Generation',
  ];